name: Multi OS Testing

on: push

jobs:
  linux-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running on Linux"

  windows-job:
    runs-on: windows-latest

    steps:
      - run: echo "Running on Windows"

  mac-job:
    runs-on: macos-latest

    steps:
      - run: echo "Running on macOS"
